#!/bin/bash

usage() {
    cat <<EOM
Usage: $(basename $0) [POD]

Enter a pod

Where 
  [POD] you wish open a shell in.

Kubernetes secrets <https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/>
Homebrew plugin <https://github.com/IestynGage/terminal>
EOM
    exit 1
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  usage
fi

kubectl exec --stdin --tty $1 -- /bin/bash`
