#!/bin/bash

usage() {
    cat <<EOM
Usage: $(basename $0) [SECRET-NAME]

Lists the secrets in the current Kubernetes namespace,
or displays the content of [SECRET-NAME].

Where 
  [SECRET-NAME] displays the content of the Kubernetes secret.

Kubernetes secrets <https://kubernetes.io/docs/concepts/configuration/secret/>

EOM
    exit 1
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  usage
fi

if [ $# -eq 0 ]
  then
    kubectl get secrets
else
  kubectl get secret $1 -o go-template='
  {{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}'
fi
